# Generated by Django 6.0.4 on 2026-04-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('delimiter', models.CharField(blank=True, max_length=10, null=True)),
                ('encoding', models.CharField(blank=True, max_length=50, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='UPLOADED', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
